### ISSUE TITLE
Can't update gist

### ISSUE THREAD

**Issue by abhisheknaiidu** [yg/todoist-box#33]
Getting this same `error` every time

<img width="1213" alt="Screenshot 2020-06-19 at 3 50 58 PM" src="https://user-images.githubusercontent.com/55599878/85123082-32069080-b245-11ea-9083-9421acf28edf.png">

My gist looks like this,

<img width="1213" alt="Screenshot 2020-06-19 at 3 51 26 PM" src="https://user-images.githubusercontent.com/55599878/85123095-3a5ecb80-b245-11ea-9805-bf6e62c75a5f.png">

**Comment by yg** [comment]
Thanks for the issue @abhisheknaiidu :purple_heart:!

To claim an issue to work on or need any help, please leave a comment :speech_balloon:

**Comment by abhisheknaiidu** [comment]
@yg It says 
`(node:832) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'total_completed' of undefined`

I am not able to figure it out, what does even it mean?

**Comment by yg** [comment]
@abhisheknaiidu Have you configured secrets with `TODOIST_API_KEY` and `GH_TOKEN`

**Comment by abhisheknaiidu** [comment]
@yg Yess I have done everything as mentioned  in the `readme`

**Comment by yg** [comment]
@abhisheknaiidu Fixed, Can you again create a new repo using this template?

**Comment by yg** [comment]
The reason is they have released some breaking changes in the API

**Comment by yg** [comment]
@abhisheknaiidu Wait this is not the fix! Some other stuff is causing the issue!

**Comment by abhisheknaiidu** [comment]
closing this, as it was fixed!🎉
